wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1708455526.217753
    t:
      1:
      - 1
      - 55
      3:
      - 23
      4: 3.11.7
      5: 0.16.3
      8:
      - 5
      13: darwin-arm64
